global:
  # domain: argocd.127.0.0.1.nip.io
  domain: argocd.localhost
configs:
  secret:
    # log in with admin:password
    argocdServerAdminPassword: "$2y$10$QpI0XbmM13sbHpxIt.C0sOAfGUwCy9w19SoSjQt1tr9kT1yHHUb4C"
    argocdServerAdminPasswordMtime: "2024-09-04T15:19:34Z"
  cm:
    application.resourceTrackingMethod: annotation
  params:
    "server.insecure": true
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
